language: node_js
node_js:
  - "6"
  - "8"
install:
  - npm install
  - npm install -g codecov
script:
  - test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
